version: 1
jobs:
  build:
    machine: true
    steps:
      # - setup_remote_docker
      - checkout
      # - run: |
      #   docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-compose build


      #https://circleci.com/docs/2.0/building-docker-images/
